[2024-11-30T20:43:21.279+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-30T20:43:21.312+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt-dag.dbt_snapshot scheduled__2024-11-29T20:40:00+00:00 [queued]>
[2024-11-30T20:43:21.320+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt-dag.dbt_snapshot scheduled__2024-11-29T20:40:00+00:00 [queued]>
[2024-11-30T20:43:21.321+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-30T20:43:21.333+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_snapshot> on 2024-11-29 20:40:00+00:00
[2024-11-30T20:43:21.342+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dbt-dag', 'dbt_snapshot', 'scheduled__2024-11-29T20:40:00+00:00', '--job-id', '438', '--raw', '--subdir', 'DAGS_FOLDER/dbt-dag.py', '--cfg-path', '/tmp/tmp506g1qpm']
[2024-11-30T20:43:21.344+0000] {standard_task_runner.py:91} INFO - Job 438: Subtask dbt_snapshot
[2024-11-30T20:43:21.353+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=3731) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-30T20:43:21.354+0000] {standard_task_runner.py:63} INFO - Started process 3732 to run task
[2024-11-30T20:43:21.390+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt-dag.dbt_snapshot scheduled__2024-11-29T20:40:00+00:00 [running]> on host e060654747dc
[2024-11-30T20:43:21.515+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt-dag' AIRFLOW_CTX_TASK_ID='dbt_snapshot' AIRFLOW_CTX_EXECUTION_DATE='2024-11-29T20:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-29T20:40:00+00:00'
[2024-11-30T20:43:21.516+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-30T20:43:21.529+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-30T20:43:21.531+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt snapshot --profiles-dir /opt/***/dbt --project-dir /opt/***/dbt']
[2024-11-30T20:43:21.542+0000] {subprocess.py:86} INFO - Output:
[2024-11-30T20:43:23.466+0000] {subprocess.py:93} INFO - [0m20:43:23  Running with dbt=1.8.7
[2024-11-30T20:43:24.507+0000] {subprocess.py:93} INFO - [0m20:43:24  Registered adapter: snowflake=1.8.4
[2024-11-30T20:43:25.088+0000] {subprocess.py:93} INFO - [0m20:43:25  Found 5 models, 1 test, 4 sources, 459 macros
[2024-11-30T20:43:25.092+0000] {subprocess.py:93} INFO - [0m20:43:25
[2024-11-30T20:43:25.093+0000] {subprocess.py:93} INFO - [0m20:43:25  Nothing to do. Try checking your model configs and model specification args
[2024-11-30T20:43:25.919+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-11-30T20:43:25.922+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-30T20:43:25.950+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dbt-dag, task_id=dbt_snapshot, run_id=scheduled__2024-11-29T20:40:00+00:00, execution_date=20241129T204000, start_date=20241130T204321, end_date=20241130T204325
[2024-11-30T20:43:26.022+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-30T20:43:26.041+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-30T20:43:26.046+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
