[2024-11-29T20:44:30.064+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-29T20:44:30.144+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Weather_Forecast.fetch_forecast_weather scheduled__2024-11-28T20:30:00+00:00 [queued]>
[2024-11-29T20:44:30.159+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Weather_Forecast.fetch_forecast_weather scheduled__2024-11-28T20:30:00+00:00 [queued]>
[2024-11-29T20:44:30.160+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-29T20:44:30.183+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): fetch_forecast_weather> on 2024-11-28 20:30:00+00:00
[2024-11-29T20:44:30.245+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Weather_Forecast', 'fetch_forecast_weather', 'scheduled__2024-11-28T20:30:00+00:00', '--job-id', '279', '--raw', '--subdir', 'DAGS_FOLDER/weather_forecast_dag.py', '--cfg-path', '/tmp/tmpz48ysyie']
[2024-11-29T20:44:30.253+0000] {standard_task_runner.py:91} INFO - Job 279: Subtask fetch_forecast_weather
[2024-11-29T20:44:30.266+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=16277) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-29T20:44:30.267+0000] {standard_task_runner.py:63} INFO - Started process 16300 to run task
[2024-11-29T20:44:32.641+0000] {task_command.py:426} INFO - Running <TaskInstance: Weather_Forecast.fetch_forecast_weather scheduled__2024-11-28T20:30:00+00:00 [running]> on host fd43cd87157f
[2024-11-29T20:44:33.476+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Weather_Forecast' AIRFLOW_CTX_TASK_ID='fetch_forecast_weather' AIRFLOW_CTX_EXECUTION_DATE='2024-11-28T20:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-28T20:30:00+00:00'
[2024-11-29T20:44:33.479+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-29T20:44:35.516+0000] {python.py:237} INFO - Done. Returned value was:          Date  temperature_2m_max  ...  windspeed_10m_max  avg_temperature
0  2024-11-29                15.6  ...               13.5             9.25
1  2024-11-30                15.3  ...               11.4            10.60
2  2024-12-01                14.8  ...               25.3             9.45
3  2024-12-02                 6.7  ...               19.0             1.90
4  2024-12-03                 9.6  ...               10.1             4.20
5  2024-12-04                 9.0  ...                9.0             3.95
6  2024-12-05                11.5  ...               15.4             6.65

[7 rows x 7 columns]
[2024-11-29T20:44:35.579+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-29T20:44:35.843+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Weather_Forecast, task_id=fetch_forecast_weather, run_id=scheduled__2024-11-28T20:30:00+00:00, execution_date=20241128T203000, start_date=20241129T204430, end_date=20241129T204435
[2024-11-29T20:44:35.986+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-29T20:44:36.033+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-29T20:44:36.045+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
