[2024-11-30T08:35:05.589+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-30T08:35:05.617+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: complete-dag.dbt_snapshot manual__2024-11-30T08:33:53.025918+00:00 [queued]>
[2024-11-30T08:35:05.628+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: complete-dag.dbt_snapshot manual__2024-11-30T08:33:53.025918+00:00 [queued]>
[2024-11-30T08:35:05.630+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-30T08:35:05.646+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_snapshot> on 2024-11-30 08:33:53.025918+00:00
[2024-11-30T08:35:05.658+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'complete-dag', 'dbt_snapshot', 'manual__2024-11-30T08:33:53.025918+00:00', '--job-id', '422', '--raw', '--subdir', 'DAGS_FOLDER/complete_dag.py', '--cfg-path', '/tmp/tmpvqhcikkm']
[2024-11-30T08:35:05.660+0000] {standard_task_runner.py:91} INFO - Job 422: Subtask dbt_snapshot
[2024-11-30T08:35:05.664+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2445) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-30T08:35:05.665+0000] {standard_task_runner.py:63} INFO - Started process 2458 to run task
[2024-11-30T08:35:05.705+0000] {task_command.py:426} INFO - Running <TaskInstance: complete-dag.dbt_snapshot manual__2024-11-30T08:33:53.025918+00:00 [running]> on host e060654747dc
[2024-11-30T08:35:05.840+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='complete-dag' AIRFLOW_CTX_TASK_ID='dbt_snapshot' AIRFLOW_CTX_EXECUTION_DATE='2024-11-30T08:33:53.025918+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-30T08:33:53.025918+00:00'
[2024-11-30T08:35:05.841+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-30T08:35:05.842+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-30T08:35:05.844+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt snapshot --profiles-dir /opt/***/dbt --project-dir /opt/***/dbt']
[2024-11-30T08:35:05.863+0000] {subprocess.py:86} INFO - Output:
[2024-11-30T08:35:08.485+0000] {subprocess.py:93} INFO - [0m08:35:08  Running with dbt=1.8.7
[2024-11-30T08:35:09.739+0000] {subprocess.py:93} INFO - [0m08:35:09  Registered adapter: snowflake=1.8.4
[2024-11-30T08:35:10.484+0000] {subprocess.py:93} INFO - [0m08:35:10  Found 5 models, 1 test, 4 sources, 459 macros
[2024-11-30T08:35:10.488+0000] {subprocess.py:93} INFO - [0m08:35:10
[2024-11-30T08:35:10.490+0000] {subprocess.py:93} INFO - [0m08:35:10  Nothing to do. Try checking your model configs and model specification args
[2024-11-30T08:35:11.351+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-11-30T08:35:11.353+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-30T08:35:11.382+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=complete-dag, task_id=dbt_snapshot, run_id=manual__2024-11-30T08:33:53.025918+00:00, execution_date=20241130T083353, start_date=20241130T083505, end_date=20241130T083511
[2024-11-30T08:35:11.425+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-30T08:35:11.435+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
