[2024-11-28T19:21:53.775+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-28T19:21:53.802+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Weather_Forecast.load_weather_data_to_snowflake manual__2024-11-28T19:21:50.284700+00:00 [queued]>
[2024-11-28T19:21:53.809+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Weather_Forecast.load_weather_data_to_snowflake manual__2024-11-28T19:21:50.284700+00:00 [queued]>
[2024-11-28T19:21:53.809+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-28T19:21:53.822+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load_weather_data_to_snowflake> on 2024-11-28 19:21:50.284700+00:00
[2024-11-28T19:21:53.832+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Weather_Forecast', 'load_weather_data_to_snowflake', 'manual__2024-11-28T19:21:50.284700+00:00', '--job-id', '224', '--raw', '--subdir', 'DAGS_FOLDER/weather_forecast_dag.py', '--cfg-path', '/tmp/tmpxt4p67fs']
[2024-11-28T19:21:53.834+0000] {standard_task_runner.py:91} INFO - Job 224: Subtask load_weather_data_to_snowflake
[2024-11-28T19:21:53.834+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=601) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-28T19:21:53.835+0000] {standard_task_runner.py:63} INFO - Started process 604 to run task
[2024-11-28T19:21:53.876+0000] {task_command.py:426} INFO - Running <TaskInstance: Weather_Forecast.load_weather_data_to_snowflake manual__2024-11-28T19:21:50.284700+00:00 [running]> on host fd43cd87157f
[2024-11-28T19:21:54.034+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Weather_Forecast' AIRFLOW_CTX_TASK_ID='load_weather_data_to_snowflake' AIRFLOW_CTX_EXECUTION_DATE='2024-11-28T19:21:50.284700+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-28T19:21:50.284700+00:00'
[2024-11-28T19:21:54.036+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-28T19:21:54.049+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-11-28T19:21:54.050+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.0, Python Version: 3.12.3, Platform: Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2024-11-28T19:21:54.052+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-11-28T19:21:54.930+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-11-28T19:21:55.283+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-11-28T19:21:55.287+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/weather_forecast_dag.py:62 FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
[2024-11-28T19:21:55.297+0000] {logging_mixin.py:188} INFO -          Date  temperature_2m_max  ...  windspeed_10m_max  avg_temperature
0  2024-11-28                12.2  ...               23.7              6.5

[1 rows x 7 columns]
[2024-11-28T19:21:56.053+0000] {logging_mixin.py:188} INFO - Successfully inserted 1 rows.
[2024-11-28T19:21:56.155+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-11-28T19:21:56.156+0000] {connection.py:762} INFO - closed
[2024-11-28T19:21:56.233+0000] {connection.py:768} INFO - No async queries seem to be running, deleting session
[2024-11-28T19:21:56.354+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-28T19:21:56.355+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-28T19:21:56.364+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Weather_Forecast, task_id=load_weather_data_to_snowflake, run_id=manual__2024-11-28T19:21:50.284700+00:00, execution_date=20241128T192150, start_date=20241128T192153, end_date=20241128T192156
[2024-11-28T19:21:56.418+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-28T19:21:56.434+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-28T19:21:56.438+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
