[2024-11-29T05:44:40.750+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-29T05:44:40.784+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Electricity_predict.predict manual__2024-11-29T05:44:34.975360+00:00 [queued]>
[2024-11-29T05:44:40.791+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Electricity_predict.predict manual__2024-11-29T05:44:34.975360+00:00 [queued]>
[2024-11-29T05:44:40.791+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-29T05:44:40.806+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): predict> on 2024-11-29 05:44:34.975360+00:00
[2024-11-29T05:44:40.825+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Electricity_predict', 'predict', 'manual__2024-11-29T05:44:34.975360+00:00', '--job-id', '264', '--raw', '--subdir', 'DAGS_FOLDER/energy_usage_prediction.py', '--cfg-path', '/tmp/tmp2wi60iqp']
[2024-11-29T05:44:40.827+0000] {standard_task_runner.py:91} INFO - Job 264: Subtask predict
[2024-11-29T05:44:40.828+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=8684) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-29T05:44:40.829+0000] {standard_task_runner.py:63} INFO - Started process 8687 to run task
[2024-11-29T05:44:40.870+0000] {task_command.py:426} INFO - Running <TaskInstance: Electricity_predict.predict manual__2024-11-29T05:44:34.975360+00:00 [running]> on host fd43cd87157f
[2024-11-29T05:44:40.957+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Electricity_predict' AIRFLOW_CTX_TASK_ID='predict' AIRFLOW_CTX_EXECUTION_DATE='2024-11-29T05:44:34.975360+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-29T05:44:34.975360+00:00'
[2024-11-29T05:44:40.958+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-29T05:45:00.366+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-11-29T05:45:00.367+0000] {energy_usage_prediction.py:107} INFO - prediction created
[2024-11-29T05:45:00.528+0000] {logging_mixin.py:188} INFO - 000904 (42000): 01b8b058-0004-3863-0002-595300031a8a: SQL compilation error: error line 3 at position 4
invalid identifier 'ELECTRICITY_VALUE_GWH'
[2024-11-29T05:45:00.529+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-29T05:45:00.530+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/energy_usage_prediction.py", line 108, in predict
    cur.execute(create_final_table_sql)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/cursor.py", line 1080, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 000904 (42000): 01b8b058-0004-3863-0002-595300031a8a: SQL compilation error: error line 3 at position 4
invalid identifier 'ELECTRICITY_VALUE_GWH'
[2024-11-29T05:45:00.541+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Electricity_predict, task_id=predict, run_id=manual__2024-11-29T05:44:34.975360+00:00, execution_date=20241129T054434, start_date=20241129T054440, end_date=20241129T054500
[2024-11-29T05:45:00.557+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 264 for task predict (000904 (42000): 01b8b058-0004-3863-0002-595300031a8a: SQL compilation error: error line 3 at position 4
invalid identifier 'ELECTRICITY_VALUE_GWH'; 8687)
[2024-11-29T05:45:00.582+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-29T05:45:00.596+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-29T05:45:00.600+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
