[2024-11-30T05:30:11.121+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-30T05:30:11.162+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt-dag.dbt_snapshot manual__2024-11-30T05:29:45.742677+00:00 [queued]>
[2024-11-30T05:30:11.176+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt-dag.dbt_snapshot manual__2024-11-30T05:29:45.742677+00:00 [queued]>
[2024-11-30T05:30:11.178+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-30T05:30:11.202+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_snapshot> on 2024-11-30 05:29:45.742677+00:00
[2024-11-30T05:30:11.211+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dbt-dag', 'dbt_snapshot', 'manual__2024-11-30T05:29:45.742677+00:00', '--job-id', '335', '--raw', '--subdir', 'DAGS_FOLDER/dbt-dag.py', '--cfg-path', '/tmp/tmpeiucylsr']
[2024-11-30T05:30:11.213+0000] {standard_task_runner.py:91} INFO - Job 335: Subtask dbt_snapshot
[2024-11-30T05:30:11.227+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=4558) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-30T05:30:11.228+0000] {standard_task_runner.py:63} INFO - Started process 4559 to run task
[2024-11-30T05:30:11.258+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt-dag.dbt_snapshot manual__2024-11-30T05:29:45.742677+00:00 [running]> on host b09a94790db6
[2024-11-30T05:30:11.397+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt-dag' AIRFLOW_CTX_TASK_ID='dbt_snapshot' AIRFLOW_CTX_EXECUTION_DATE='2024-11-30T05:29:45.742677+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-30T05:29:45.742677+00:00'
[2024-11-30T05:30:11.398+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-30T05:30:11.413+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-30T05:30:11.418+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt snapshot --profiles-dir /opt/***/dbt --project-dir /opt/***/dbt']
[2024-11-30T05:30:11.432+0000] {subprocess.py:86} INFO - Output:
[2024-11-30T05:30:13.485+0000] {subprocess.py:93} INFO - [0m05:30:13  Running with dbt=1.8.7
[2024-11-30T05:30:14.515+0000] {subprocess.py:93} INFO - [0m05:30:14  Registered adapter: snowflake=1.8.4
[2024-11-30T05:30:15.218+0000] {subprocess.py:93} INFO - [0m05:30:15  Found 7 models, 1 test, 4 sources, 459 macros
[2024-11-30T05:30:15.222+0000] {subprocess.py:93} INFO - [0m05:30:15
[2024-11-30T05:30:15.224+0000] {subprocess.py:93} INFO - [0m05:30:15  Nothing to do. Try checking your model configs and model specification args
[2024-11-30T05:30:16.052+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-11-30T05:30:16.054+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-30T05:30:16.098+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dbt-dag, task_id=dbt_snapshot, run_id=manual__2024-11-30T05:29:45.742677+00:00, execution_date=20241130T052945, start_date=20241130T053011, end_date=20241130T053016
[2024-11-30T05:30:16.143+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-30T05:30:16.163+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-30T05:30:16.167+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
